#!/usr/bin/env bash
# Load functions and variables
. /usr/bin/common
PALEN1X_VERSION="1.1.0"

export NEWT_COLORS='root=,black
border=white,black
title=white,black
roottext=red,black
window=red,black
textbox=white,black
button=black,green
compactbutton=white,black
listbox=white,black
actlistbox=black,white
actsellistbox=black,green
checkbox=green,black
actcheckbox=black,green
'

whiptail_height="$(($(tput lines) - 6))"
whiptail_width="$(($(tput cols) - 20))"

while true; do
  CHOICE="$(whiptail --nocancel --title "palen1x - actions $PALEN1X_VERSION | use arrow keys" --menu '' $whiptail_height $whiptail_width 9 \
    '1' 'Respring' \
    '2' 'UICache' \
    '3' 'Reload palera1n loader' \
    '4' 'Exit' 3>&1 1>&2 2>&3)"
  case "$CHOICE" in
    1)
      clear
      /usr/bin/respring_action
      ;;
    2)
      clear
      /usr/bin/uicache_action
      ;;
    3)
      clear
      /usr/bin/reload_palera1n_loader_menu
      ;;
    4)
      clear
      /usr/bin/palen1x_menu
      ;;
  esac
done
