#!/usr/bin/env bash
# Load functions and variables
. /usr/bin/common
# Display ssh logo
ssh_logo

echo "Connect your iDevice to this computer"
read -p "Enter to continue."
clear

blue_echo 'Connecting to iDevice...'
# Can respring as the mobile user
ssh -o "ProxyCommand=inetcat 22" -o "UserKnownHostsFile=/dev/null" \
    mobile@iPhone "bash -c 'killall -9 SpringBoard'" || \
    failed_echo 'Failed to SSH into your iDevice.'
enter_to_quit
